<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class McmcStaff extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $table = 'mcmc_staff';
    protected $primaryKey = 'staff_ID';
    public $timestamps = false;

    protected $fillable = [
        'staff_Name',
        'staff_Email',
        'staff_Password',
        'staff_Role',
        'staff_First_Time_Login',
        'staff_Created_At',
        'staff_Updated_At'
    ];

    protected $hidden = [
        'staff_Password',
    ];

    protected $casts = [
        'staff_First_Time_Login' => 'boolean',
        'staff_Created_At' => 'datetime',
        'staff_Updated_At' => 'datetime',
    ];

    /**
     * Get the password attribute name for authentication
     */
    public function getAuthPassword()
    {
        return $this->staff_Password;
    }

    /**
     * Get the unique identifier for the user
     */
    public function getAuthIdentifierName()
    {
        return 'staff_ID';
    }

    /**
     * Get the unique identifier for the user
     */
    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Get the name of the unique identifier for the user
     */
    public function getKeyName()
    {
        return 'staff_ID';
    }

    /**
     * Get the approvals made by this staff member
     */
    public function approvals()
    {
        return $this->hasMany(Approval::class, 'staff_ID', 'staff_ID');
    }

    /**
     * Get the assignments made by this staff member
     */
    public function assignments()
    {
        return $this->hasMany(InquiryAssignment::class, 'assigned_By', 'staff_ID');
    }

    /**
     * Get the reports generated by this staff member
     */
    public function reports()
    {
        return $this->hasMany(Report::class, 'staff_ID', 'staff_ID');
    }

    /**
     * Get the inquiry progress records updated by this staff member
     */
    public function progressRecords()
    {
        return $this->hasMany(InquiryProgress::class, 'staff_ID', 'staff_ID');
    }

    /**
     * Check if this is the first time login
     */
    public function isFirstTimeLogin()
    {
        return $this->staff_First_Time_Login === true;
    }

    /**
     * Get formatted staff role
     */
    public function getFormattedRoleAttribute()
    {
        return ucfirst(str_replace('_', ' ', $this->staff_Role));
    }

    /**
     * Check if staff is admin
     */
    public function isAdmin()
    {
        return $this->staff_Role === 'admin';
    }

    /**
     * Check if staff is supervisor
     */
    public function isSupervisor()
    {
        return in_array($this->staff_Role, ['admin', 'supervisor']);
    }

    /**
     * Scope a query to only include active staff
     */
    public function scopeActive($query)
    {
        return $query->whereNotNull('staff_Email');
    }

    /**
     * Scope a query to filter by role
     */
    public function scopeByRole($query, $role)
    {
        return $query->where('staff_Role', $role);
    }

    /**
     * Mark first time login as completed
     */
    public function markFirstLoginCompleted()
    {
        $this->staff_First_Time_Login = false;
        $this->staff_Updated_At = now();
        $this->save();
    }
}
